let parameter = [ 'E. coli',
  'Lead',
  'Nitrate',
  'Nitrite (at tap)',
  'Aluminium',
  'Ammonium',
  'Clostridium Perfringens',
  'Colour',
  'Conductivity',
  'pH',
  'Iron',
  'Odour',
  'Taste',
  'Coliform Bacteria',
  'Turbidity (at tap)',
  'Total Chlorine',
  'Free Chlorine',
  'Cyanide',
  'Pesticides - Total',
  'PAH',
  'Benzo(a)pyrene',
  'Bromate',
  'Cadmium',
  'Chromium',
  'Copper',
  '1,2-dichloroethane',
  'Fluoride',
  'Mercury',
  'Nickel',
  'Enterococci',
  'Selenium',
  'Tetrachloroethene & Trichloroethene',
  'Trihalomethanes(Total)',
  'Vinyl Chloride',
  'Chloride',
  'Manganese',
  'Antimony',
  'Sulphate',
  'Sodium',
  'Colony Count @ 22Â°C',
  'Total Organic Carbon',
  'Arsenic',
  'Hardness (as CaCO3)',
  'Benzene',
  'Boron',
  'Cryptosporidium',
  'Hardness (as Ca)',
  'Giardia',
  'Turbidity (at WTW)',
  'Epichlorohydrin',
  'Acrylamide',
  'Tritium',
  'Total Indicative Dose',
  'Nitrites (at WTW)',
  'Oxidisability' ]
module.exports = parameter
